---
system: osx
os: osx
home: "{{ lookup('env', 'HOME') }}"

executables:
    brew: /usr/local/bin/brew
    bash: /usr/local/bin/bash

user:
    name: flynn
    group: staff
    shell: "{{ executables.bash }}"

base_osx:
    common:
        homebrew_packages:
            - ack
            - armmbed/formulae/arm-none-eabi-gcc
            - autoconf
            - automake
            - avrdude
            - bash
            - bash-completion
            - berkeley-db
            - bitwarden-cli
            - cargo-completion
            - cmake
            - coreutils
            - ctags
            - ctags-exuberant
            - diff-so-fancy
            - django-completion
            - docker
            - docker-compose
            - ffmpeg
            - flac
            - fontconfig
            - freetype
            - gcc
            - gdb
            - gem-completion
            - geoip
            - gettext
            - git
            - git-hooks
            - glide
            - gnuradio
            - gnutls
            - go
            - gr-osmosdr
            - grip
            - gtk+
            - hackrf
            - hg
            - htop-osx
            - hub
            - jq
            - ldns
            - libav
            - libjpeg
            - librtlsdr
            - libxml2
            - liquidprompt
            - lua
            - luajit
            - makedepend
            - mercurial
            - mosquitto
            - mpfr
            - msgpack
            - mysql-client
            - ncurses
            - neovim
            - nmap
            - node
            - numpy
            - picocom
            - pinentry
            - pip-completion
            - pkg-config
            - platformio
            - pre-commit
            - pwgen
            - pyenv
            - pyenv-virtualenv
            - pygobject
            - pygtk
            - pyqt
            - python3
            - qt
            - qwt
            - rails-completion
            - rake-completion
            - rbenv
            - readline
            - qemu
            - reattach-to-user-namespace
            - redis
            - ripgrep
            - rtmpdump
            - rubberband
            - ruby-build
            - ruby-completion
            - rustc-completion
            - sox
            - sphinx-doc
            - sqlite
            - ssh-copy-id
            - swig
            - syncthing
            - tag
            - telnet
            - theora
            - tmux
            - unrar
            - watch
            - wget
            - wireshark
            - yarn-completion
            - youtube-dl
            - zeromq
            - zlib

        dotfiles:
            - bashrc
            - bash_profile
            - tmux.conf
            - tmuxp
            - gitconfig
            - gitignore
            - bash_gpg
            - hammerspoon
            - iterm2_shell_integration.bash
        python3_packages:
            - GitPython
            - ipython
            - virtualenv
            - virtualenvwrapper
        python_packages:
            - GitPython
            - grip
            - ipython
            - pip
            - powerline-status
            - psutil
            - tmuxp
        launch_agents:
            - local.brew.update.plist
            - local.brew.cleanup.plist
