---
- name: packages | Install zypper items
  become: true
  zypper:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - "{{ base_opensuse.common.packages }}"
  tags:
      - packages

- name: packages | Install flatpak items
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
    method: system
  loop:
    - "{{ base_opensuse.common.flatpak }}"
