---
- name: common | Create ~/.ssh/
  file: path={{ home }}/.local/share/nvim/site/autoload
        state=directory

- name: vim | Clone .vim/
  git: repo=https://github.com/flynnguy/neovim_config.git
       dest={{ home }}/.vim/
       track_submodules=yes
       update=no

- name: vim | autoload dir
  file: path={{ home }}/.vim/autoload
        state=directory

- name: vim | Get Plug vim
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
           dest={{ home }}/.vim/autoload/plug.vim

- name: vim | Get Plug neovim
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
           dest={{ home }}/.local/share/nvim/site/autoload/plug.vim

- name: vim | Check if powerline-fonts are installed already
  stat: path={{ home }}/src/powerline-fonts
  register: powerline_fonts

- name: vim | Get powerline-fonts
  git: repo=https://github.com/powerline/fonts.git
       dest={{ home }}/src/powerline-fonts
       clone=no
       update=no
  when: powerline_fonts.stat.isdir is defined and powerline_fonts.stat.isdir == False

- name: vim | Open powerline font dir if we checked it out
  command: /usr/bin/open {{ home }}/src/powerline-fonts/SourceCodePro/
  when: powerline_fonts.stat.isdir is defined and powerline_fonts.stat.isdir == False

- name: vim | Install Plugins
  command: vim +PlugInstall +qall

- name: neovim | Install Plugins
  command: nvim +PlugInstall +qall
